version: '3.7'

networks:
    workshop_sqli-symfony_net:

services:
    # The web server + PHP
    webserver:
        build:
            context: .
            dockerfile: ./docker/server/Dockerfile
        container_name: '${APP_NAME}-server'
        expose:
            - "9000"
            - "9003"
        ports:
            - '80:80'
        working_dir: /var/www/html
        environment: # Careful with this. It overwrite all connection configs of Symfony Project.
            - 'DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASS}@db_server:3306/${MYSQL_DB}?serverVersion=10.5'
        volumes:
            - ./codebase:/var/www/html
            - ./docker/server/apache/sites-enabled:/etc/apache2/sites-enabled
            - ./docker/server/php/php.ini:/usr/local/etc/php/conf.d/extra-php-config.ini
            - ./docker/xdebug/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
        depends_on:
            - mysqlserver
        networks:
            - workshop_sqli-symfony_net

    # MySQL
    mysqlserver:
        image: mariadb:10.5.9
        container_name: '${APP_NAME}-db'
        restart: always
        ports:
            - '${DB_PORT}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASS}'
            MYSQL_USER: '${MYSQL_USER}'
            MYSQL_PASSWORD: '${MYSQL_PASS}'
            MYSQL_DATABASE: '${MYSQL_DB}'
        volumes:
            - db_data:/var/lib/mysql
            - ./docker/db/mariadb/my.cnf:/etc/mysql/conf.d/my.cnf
        healthcheck:
            test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
            interval: 5s
            retries: 5
        networks:
            - workshop_sqli-symfony_net

    # the PhpMyAdmin
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:5
        container_name: '${APP_NAME}-db-admin'
        ports:
            - '${APP_DB_ADMIN_PORT}:80'
        environment:
            PMA_HOST: webserver
        depends_on:
            - webserver
        volumes:
            - db_admin_data:/var/www/html
        networks:
            - workshop_sqli-symfony_net

    # Mail server
    mailcatcher:
        container_name: '${APP_NAME}-mailer'
        networks:
            - workshop_sqli-symfony_net
        image: yappabe/mailcatcher
        ports:
            - 1025:1025
            - 1080:1080
    
volumes:
    db_data:
    db_admin_data:
